swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: "<iframe src='<script>alert(1)</script>'><details open=''>"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
