swagger: '2.0'
info:
  version: "0.0.1"
  title: Example Title
  description: "><embed src=x>"
  Default: <script>console.log(‘000000000000000000dad0000000000000000000');</script>
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
